// Generated by stratus_hls 23.02-s002  (100118.310516)
// Thu Nov 13 00:44:14 2025
// from dut.cc
#ifndef CYNTH_PART_dut_dut_rtl_h
#define CYNTH_PART_dut_dut_rtl_h

#include "systemc.h"
#include "stratus_hls.h"
/* Include declarations of instantiated parts. */


/* Declaration of the synthesized module. */
struct dut : public sc_module {
  sc_in<bool > clk;
  sc_in<bool > rst;
  sc_out<bool > din_busy;
  sc_in<bool > din_vld;
  sc_in<sc_uint<8> > din_data;
  sc_in<bool > dout_busy;
  sc_out<bool > dout_vld;
  sc_out<sc_uint<11> > dout_data;
  dut( sc_module_name name );
  SC_HAS_PROCESS(dut);
  sc_signal<bool > dout_m_req_m_prev_trig_req;
  sc_signal<sc_uint<1> > dut_Xor_1Ux1U_1U_1_1_out1;
  sc_signal<bool > dout_m_unacked_req;
  sc_signal<sc_uint<1> > dut_Or_1Ux1U_1U_4_2_out1;
  sc_signal<sc_uint<1> > dut_N_Muxb_1_2_8_4_4_out1;
  sc_signal<bool > din_m_unvalidated_req;
  sc_signal<sc_uint<1> > 
  dut_gen_busy_r_4_9_din_gen_busy_din_m_data_is_invalid_next;
  sc_signal<sc_uint<1> > dut_gen_busy_r_4_9_gdiv;
  sc_signal<sc_uint<1> > dut_gen_busy_r_4_9_gnew_req;
  sc_signal<sc_uint<2> > global_state_next;
  sc_signal<sc_uint<3> > dut_gen_busy_r_4_9_out1;
  sc_signal<sc_uint<1> > dut_And_1Ux1U_1U_4_7_out1;
  sc_signal<sc_uint<1> > dut_Not_1U_1U_1_3_out1;
  sc_signal<bool > dout_m_req_m_trig_req;
  sc_signal<bool > din_m_busy_req_0;
  sc_signal<sc_uint<11> > dut_Mul_11U_0_4_6_out1;
  sc_signal<sc_uint<2> > global_state;
  sc_signal<sc_uint<1> > stall0;
  void drive_dout_data();
  void drive_din_m_busy_req_0();
  void drive_dout_m_req_m_trig_req();
  void drive_stall0();
  void drive_global_state();
  void dut_Mul_11U_0_4_6();
  void drive_global_state_next();
  void drive_din_busy();
  void dut_gen_busy_r_4_9_p7();
  void dut_gen_busy_r_4_9_p6();
  void dut_gen_busy_r_4_9_p5();
  void dut_gen_busy_r_4_9_p4();
  void drive_din_m_unvalidated_req();
  void dut_N_Muxb_1_2_8_4_4();
  void drive_dout_vld();
  void dut_Or_1Ux1U_1U_4_2();
  void drive_dout_m_unacked_req();
  void dut_And_1Ux1U_1U_4_7();
  void dut_Xor_1Ux1U_1U_1_1();
  void drive_dout_m_req_m_prev_trig_req();
  void dut_Not_1U_1U_1_3();
};

#endif
