// Generated by stratus_hls 23.02-s002  (100118.310516)
// Thu Nov 13 00:44:14 2025
// from dut.cc

`timescale 1ps / 1ps


module dut( clk, rst, din_busy, din_vld, din_data, dout_busy, dout_vld, dout_data );

    input clk;
    input rst;
    input din_vld;
    input [7:0] din_data;
    input dout_busy;
    output din_busy;
    output dout_vld;
    output [10:0] dout_data;
    reg [10:0] dout_data;
    reg  dout_m_req_m_prev_trig_req;
    reg  dout_m_unacked_req;
    wire  dut_Xor_1Ux1U_1U_1_1_out1;
    wire  dut_Or_1Ux1U_1U_4_2_out1;
    reg  dut_N_Muxb_1_2_8_4_4_out1;
    reg  din_m_unvalidated_req;
    wire  dut_gen_busy_r_4_9_gnew_req;
    wire  dut_gen_busy_r_4_9_gdiv;
    wire  dut_gen_busy_r_4_9_din_gen_busy_din_m_data_is_invalid_next;
    reg [1:0] global_state_next;
    wire  dut_And_1Ux1U_1U_4_7_out1;
    wire [2:0] dut_gen_busy_r_4_9_out1;
    wire  dut_Not_1U_1U_1_3_out1;
    reg  dout_m_req_m_trig_req;
    reg  din_m_busy_req_0;
    wire [10:0] dut_Mul_11U_0_4_6_out1;
    reg [1:0] global_state;
    reg  stall0;

    
    // rtl_process:dut/drive_dout_data
    // Sharing or Control mux
    // Sharing/Controlling 1 operation(s) on drive_dout_data
    // at: cynw_p2p.h:5330:13
    
    always @(posedge clk)
      begin : drive_dout_data
        case (stall0) 
          1'b1: 
            begin
            end
          default: 
            begin
              case (global_state) 
                2'd1: 
                  begin
                    // op:thread_function/OP46
                    // at: cynw_p2p.h:5330:13
                    // Call Stack: 
                    // in function nb_put_work called from cynw_p2p.h:5093:7
                    // in function put called from dut.cc:49:14
                    dout_data <= dut_Mul_11U_0_4_6_out1;
                  end
              endcase
            end
        endcase
      end
    
    // rtl_process:dut/drive_din_m_busy_req_0
    // Sharing or Control mux
    // Sharing/Controlling 5 operation(s) on drive_din_m_busy_req_0
    // at: cynw_p2p.h:1817:17
    // at: cynw_p2p.h:1515:2
    // at: cynw_p2p.h:1599:7
    // at: cynw_p2p.h:1631:7
    // at: cynw_p2p.h:1772:12
    
    always @(posedge clk)
      begin : drive_din_m_busy_req_0
        if (rst == 1'b0) 
          begin
            // op:thread_function/OP37
            // at: cynw_p2p.h:1515:2
            // Call Stack: 
            // in function reset called from dut.cc:35:13
            din_m_busy_req_0 <= 1'd1;
          end 
        else 
          begin
            case (stall0) 
              1'b1: 
                begin
                end
              default: 
                begin
                  case (global_state) 
                    2'd0, 2'd2: 
                      begin
                        // op:thread_function/OP40
                        // at: cynw_p2p.h:1599:7
                        // Call Stack: 
                        // in function get_start called from cynw_p2p.h:1455:7
                        // in function get called from dut.cc:44:27
                        din_m_busy_req_0 <= 1'd0;
                      end
                    2'd1: 
                      begin
                        // op:thread_function/OP43
                        // at: cynw_p2p.h:1631:7
                        // Call Stack: 
                        // in function get_end called from cynw_p2p.h:1478:7
                        // in function get called from dut.cc:44:27
                        din_m_busy_req_0 <= 1'd1;
                      end
                  endcase
                end
            endcase
          end
      end
    
    // rtl_process:dut/drive_dout_m_req_m_trig_req
    // Sharing or Control mux
    // Sharing/Controlling 5 operation(s) on drive_dout_m_req_m_trig_req
    // at: cynw_comm_util.h:1458:27
    // at: cynw_comm_util.h:1442:52
    // at: cynw_comm_util.h:1483:26
    // at: cynw_comm_util.h:1401:7
    // at: cynw_comm_util.h:1394:2
    
    always @(posedge clk)
      begin : drive_dout_m_req_m_trig_req
        if (rst == 1'b0) 
          begin
            // op:thread_function/OP39
            // at: cynw_comm_util.h:1401:7
            // Call Stack: 
            // in function reset called from cynw_p2p.h:5122:13
            // in function reset called from dut.cc:36:14
            dout_m_req_m_trig_req <= 1'd0;
          end 
        else 
          begin
            case (stall0) 
              1'b1: 
                begin
                end
              default: 
                begin
                  case (global_state) 
                    2'd1: 
                      begin
                        // op:thread_function/OP48
                        // at: cynw_comm_util.h:1394:2
                        // Call Stack: 
                        // in function trig called from cynw_p2p.h:5331:8
                        // in function nb_put_work called from cynw_p2p.h:5093:7
                        // in function put called from dut.cc:49:14
                        dout_m_req_m_trig_req <= dut_Not_1U_1U_1_3_out1;
                      end
                  endcase
                end
            endcase
          end
      end
    
    // rtl_process:dut/drive_stall0
    // Sharing or Control mux
    // Sharing/Controlling 4 operation(s) on drive_stall0
    // at: cynw_p2p.h:1860:47
    // at: cynw_p2p.h:1535:33
    // at: cynw_p2p.h:1464:9
    // at: cynw_p2p.h:5106:2
    always @*
      begin : drive_stall0
        case (global_state) 
          2'd1: 
            begin
              // op:thread_function/OP42
              // at: cynw_p2p.h:1464:9
              // Call Stack: 
              // in function get called from dut.cc:44:27
              stall0 = dut_gen_busy_r_4_9_out1[0];
            end
          2'd2: 
            begin
              // op:thread_function/OP50
              // at: cynw_p2p.h:5106:2
              // Call Stack: 
              // in function put called from dut.cc:49:14
              stall0 = dut_And_1Ux1U_1U_4_7_out1;
            end
          default: 
            begin
              stall0 = 1'b0;
            end
        endcase
      end
    
    // rtl_process:dut/drive_global_state
    // FSM Control Mux
    // FSM Control for thread behavior:thread_function
    // BB3 : PROTO_1
    //   SRCLOC: dut.cc:38:9
    //    FSM: global_state == 0
    // BB7 : PROTO_2
    //   SRCLOC: cynw_p2p.h:1466:11
    //    FSM: global_state == 1
    // BB12 : PROTO_3
    //   SRCLOC: cynw_p2p.h:5108:4
    //    FSM: global_state == 2
    
    always @(posedge clk)
      begin : drive_global_state
        if (rst == 1'b0) 
          begin
            // basic_block:din_gen_busy/BB3
            global_state <= 2'd0;
          end 
        else 
          begin
            case (stall0) 
              1'b1: 
                begin
                end
              default: 
                begin
                  global_state <= global_state_next;
                end
            endcase
          end
      end
    
    // rtl_instance:dut/dut_Mul_11U_0_4_6
    // Resource=dut_Mul_11U_0_4, Function=mul : Inputs=8 Outputs=11
    // Implements 1 operation(s)
    // at: dut.cc:57:18
    assign dut_Mul_11U_0_4_6_out1 = {3'b000, din_data} * 11'd0007;
    
    // rtl_process:dut/drive_global_state_next
    // FSM Control Mux
    // FSM Control for thread behavior:thread_function
    always @*
      begin : drive_global_state_next
        case (global_state) 
          2'd0, 2'd2: 
            begin
              // basic_block:thread_function/BB7
              global_state_next = 2'd1;
            end
          default: 
            begin
              // basic_block:thread_function/BB12
              global_state_next = 2'd2;
            end
        endcase
      end
    
    // rtl_process:dut/drive_din_busy
    // Sharing or Control mux
    // Sharing/Controlling 1 operation(s) on drive_din_busy
    // at: cynw_p2p.h:1782:13
    assign din_busy = dut_gen_busy_r_4_9_out1[2];
    
    // rtl_instance:dut/dut_gen_busy_r_4_9 (4 concurrent statements)
    // Resource=dut_gen_busy_r_4, Function=not not and and or : Inputs=1,1,1 Outputs=3
    // Implements 1 operation(s)
    // at: cynw_p2p.h:1750:8
      assign dut_gen_busy_r_4_9_out1 = {dut_gen_busy_r_4_9_gnew_req, {dut_gen_busy_r_4_9_gdiv, dut_gen_busy_r_4_9_din_gen_busy_din_m_data_is_invalid_next}};
      assign dut_gen_busy_r_4_9_din_gen_busy_din_m_data_is_invalid_next = ~dut_gen_busy_r_4_9_gdiv;
      assign dut_gen_busy_r_4_9_gdiv = din_vld & !dut_gen_busy_r_4_9_gnew_req;
      assign dut_gen_busy_r_4_9_gnew_req = din_m_busy_req_0 & (din_m_unvalidated_req | din_vld);
    // (end of dut_gen_busy_r_4_9)
    
    // rtl_process:dut/drive_din_m_unvalidated_req
    // Sharing or Control mux
    // Sharing/Controlling 4 operation(s) on drive_din_m_unvalidated_req
    // at: cynw_p2p.h:1813:2
    // at: cynw_p2p.h:1807:10
    // at: cynw_p2p.h:1818:13
    // at: cynw_p2p.h:1772:36
    
    always @(posedge clk)
      begin : drive_din_m_unvalidated_req
        if (rst == 1'b0) 
          begin
            // op:din_gen_unvalidated_req/OP19
            // at: cynw_p2p.h:1813:2
            // Call Stack: 
            // in function gen_unvalidated_req called from cynw_p2p.h:1813:2
            din_m_unvalidated_req <= 1'd1;
          end 
        else 
          begin
            case (!din_m_busy_req_0) 
              1'b1: 
                begin
                  // op:din_gen_unvalidated_req/OP25
                  // at: cynw_p2p.h:1818:13
                  // Call Stack: 
                  // in function gen_unvalidated_req called from cynw_p2p.h:1818:13
                  din_m_unvalidated_req <= dut_N_Muxb_1_2_8_4_4_out1;
                end
              default: 
                begin
                end
            endcase
          end
      end
    
    // rtl_instance:dut/dut_N_Muxb_1_2_8_4_4
    // Resource=dut_N_Muxb_1_2_8_4, Function=mux : Inputs=1,1,1 Outputs=1
    // Implements 1 operation(s)
    // at: cynw_p2p.h:1817:11
    always @*
      begin : dut_N_Muxb_1_2_8_4_4
        if (din_m_busy_req_0) 
          begin
            dut_N_Muxb_1_2_8_4_4_out1 = din_m_unvalidated_req;
          end 
        else 
          begin
            dut_N_Muxb_1_2_8_4_4_out1 = din_vld;
          end
      end
    
    // rtl_process:dut/drive_dout_vld
    // Sharing or Control mux
    // Sharing/Controlling 1 operation(s) on drive_dout_vld
    // at: cynw_p2p.h:5196:18
    assign dout_vld = dut_Or_1Ux1U_1U_4_2_out1;
    
    // rtl_instance:dut/dut_Or_1Ux1U_1U_4_2
    // Resource=dut_Or_1Ux1U_1U_4, Function=or : Inputs=1,1 Outputs=1
    // Implements 1 operation(s)
    // at: cynw_p2p.h:5196:50
    assign dut_Or_1Ux1U_1U_4_2_out1 = dout_m_unacked_req | dut_Xor_1Ux1U_1U_1_1_out1;
    
    // rtl_process:dut/drive_dout_m_unacked_req
    // Sharing or Control mux
    // Sharing/Controlling 3 operation(s) on drive_dout_m_unacked_req
    // at: cynw_p2p.h:5196:29
    // at: cynw_p2p.h:5208:9
    // at: cynw_p2p.h:5211:9
    
    always @(posedge clk)
      begin : drive_dout_m_unacked_req
        if (rst == 1'b0) 
          begin
            // op:dout_gen_unacked_req/OP58
            // at: cynw_p2p.h:5208:9
            // Call Stack: 
            // in function gen_unacked_req called from cynw_p2p.h:5208:9
            dout_m_unacked_req <= 1'd0;
          end 
        else 
          begin
            // op:dout_gen_unacked_req/OP60
            // at: cynw_p2p.h:5211:9
            // Call Stack: 
            // in function gen_unacked_req called from cynw_p2p.h:5211:9
            dout_m_unacked_req <= dut_And_1Ux1U_1U_4_7_out1;
          end
      end
    
    // rtl_instance:dut/dut_And_1Ux1U_1U_4_7
    // Resource=dut_And_1Ux1U_1U_4, Function=and : Inputs=1,1 Outputs=1
    // Implements 1 operation(s)
    // at: cynw_p2p.h:5223:43
    assign dut_And_1Ux1U_1U_4_7_out1 = dout_busy & dout_vld;
    
    // rtl_instance:dut/dut_Xor_1Ux1U_1U_1_1
    // Resource=dut_Xor_1Ux1U_1U_1, Function=xor : Inputs=1,1 Outputs=1
    // Implements 1 operation(s)
    // at: cynw_comm_util.h:1442:70
    assign dut_Xor_1Ux1U_1U_1_1_out1 = dout_m_req_m_trig_req ^ dout_m_req_m_prev_trig_req;
    
    // rtl_process:dut/drive_dout_m_req_m_prev_trig_req
    // Sharing or Control mux
    // Sharing/Controlling 3 operation(s) on drive_dout_m_req_m_prev_trig_req
    // at: cynw_comm_util.h:1455:9
    // at: cynw_comm_util.h:1458:9
    // at: cynw_comm_util.h:1442:73
    
    always @(posedge clk)
      begin : drive_dout_m_req_m_prev_trig_req
        if (rst == 1'b0) 
          begin
            // op:dout_m_req_gen_prev_trig_reg/OP0
            // at: cynw_comm_util.h:1455:9
            // Call Stack: 
            // in function gen_prev_trig_reg called from cynw_comm_util.h:1455:9
            dout_m_req_m_prev_trig_req <= 1'd0;
          end 
        else 
          begin
            // op:dout_m_req_gen_prev_trig_reg/OP2
            // at: cynw_comm_util.h:1458:9
            // Call Stack: 
            // in function gen_prev_trig_reg called from cynw_comm_util.h:1458:9
            dout_m_req_m_prev_trig_req <= dout_m_req_m_trig_req;
          end
      end
    
    // rtl_instance:dut/dut_Not_1U_1U_1_3
    // Resource=dut_Not_1U_1U_1, Function=not : Inputs=1 Outputs=1
    // Implements 1 operation(s)
    // at: cynw_comm_util.h:1483:25
    assign dut_Not_1U_1U_1_3_out1 = !dout_m_req_m_trig_req;

endmodule


