// Generated by stratus_hls 23.02-s002  (100118.310516)
// Thu Nov 13 00:44:14 2025
// from dut.cc
#include "dut_rtl.h"

struct dut;
dut::dut(sc_module_name name) : sc_module(name) 
    ,clk("clk")
    ,rst("rst")
    ,din_busy("din_busy")
    ,din_vld("din_vld")
    ,din_data("din_data")
    ,dout_busy("dout_busy")
    ,dout_vld("dout_vld")
    ,dout_data("dout_data")
    ,dout_m_req_m_prev_trig_req("dout_m_req_m_prev_trig_req")
    ,dut_Xor_1Ux1U_1U_1_1_out1("dut_Xor_1Ux1U_1U_1_1_out1")
    ,dout_m_unacked_req("dout_m_unacked_req")
    ,dut_Or_1Ux1U_1U_4_2_out1("dut_Or_1Ux1U_1U_4_2_out1")
    ,dut_N_Muxb_1_2_8_4_4_out1("dut_N_Muxb_1_2_8_4_4_out1")
    ,din_m_unvalidated_req("din_m_unvalidated_req")
    ,dut_gen_busy_r_4_9_din_gen_busy_din_m_data_is_invalid_next("dut_gen_busy_r_4_9_din_gen_busy_din_m_data_is_invalid_next")
    ,dut_gen_busy_r_4_9_gdiv("dut_gen_busy_r_4_9_gdiv")
    ,dut_gen_busy_r_4_9_gnew_req("dut_gen_busy_r_4_9_gnew_req")
    ,global_state_next("global_state_next")
    ,dut_gen_busy_r_4_9_out1("dut_gen_busy_r_4_9_out1")
    ,dut_And_1Ux1U_1U_4_7_out1("dut_And_1Ux1U_1U_4_7_out1")
    ,dut_Not_1U_1U_1_3_out1("dut_Not_1U_1U_1_3_out1")
    ,dout_m_req_m_trig_req("dout_m_req_m_trig_req")
    ,din_m_busy_req_0("din_m_busy_req_0")
    ,dut_Mul_11U_0_4_6_out1("dut_Mul_11U_0_4_6_out1")
    ,global_state("global_state")
    ,stall0("stall0")
{
  SC_METHOD(drive_dout_data);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_din_m_busy_req_0);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_dout_m_req_m_trig_req);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(drive_stall0);
  sensitive << ( global_state );
  sensitive << ( dut_gen_busy_r_4_9_out1 );
  sensitive << ( dut_And_1Ux1U_1U_4_7_out1 );

  SC_METHOD(drive_global_state);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(dut_Mul_11U_0_4_6);
  sensitive << ( din_data );

  SC_METHOD(drive_global_state_next);
  sensitive << ( global_state );

  SC_METHOD(drive_din_busy);
  sensitive << ( dut_gen_busy_r_4_9_out1 );

  SC_METHOD(dut_gen_busy_r_4_9_p7);
  sensitive << ( dut_gen_busy_r_4_9_din_gen_busy_din_m_data_is_invalid_next );
  sensitive << ( dut_gen_busy_r_4_9_gdiv );
  sensitive << ( dut_gen_busy_r_4_9_gnew_req );

  SC_METHOD(dut_gen_busy_r_4_9_p6);
  sensitive << ( dut_gen_busy_r_4_9_gdiv );

  SC_METHOD(dut_gen_busy_r_4_9_p5);
  sensitive << ( dut_gen_busy_r_4_9_gnew_req );
  sensitive << ( din_vld );

  SC_METHOD(dut_gen_busy_r_4_9_p4);
  sensitive << ( din_vld );
  sensitive << ( din_m_unvalidated_req );
  sensitive << ( din_m_busy_req_0 );

  SC_METHOD(drive_din_m_unvalidated_req);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(dut_N_Muxb_1_2_8_4_4);
  sensitive << ( din_m_busy_req_0 );
  sensitive << ( din_m_unvalidated_req );
  sensitive << ( din_vld );

  SC_METHOD(drive_dout_vld);
  sensitive << ( dut_Or_1Ux1U_1U_4_2_out1 );

  SC_METHOD(dut_Or_1Ux1U_1U_4_2);
  sensitive << ( dut_Xor_1Ux1U_1U_1_1_out1 );
  sensitive << ( dout_m_unacked_req );

  SC_METHOD(drive_dout_m_unacked_req);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(dut_And_1Ux1U_1U_4_7);
  sensitive << ( dout_vld );
  sensitive << ( dout_busy );

  SC_METHOD(dut_Xor_1Ux1U_1U_1_1);
  sensitive << ( dout_m_req_m_prev_trig_req );
  sensitive << ( dout_m_req_m_trig_req );

  SC_METHOD(drive_dout_m_req_m_prev_trig_req);
  sensitive << clk.pos();
  dont_initialize();

  SC_METHOD(dut_Not_1U_1U_1_3);
  sensitive << ( dout_m_req_m_trig_req );

}
// resource: regr_en_11
void dut::drive_dout_data(){
  switch( (sc_uint<1>)(stall0.read()) ) {
  case 1ULL: 
    break;
  default:
    switch( (sc_uint<2>)(global_state.read()) ) {
    case 1ULL: 
      dout_data = dut_Mul_11U_0_4_6_out1.read();
      break;
    }
    break;
  }
}
// resource: mux_1bx2i2c
// resource: regr_en_ss_1
void dut::drive_din_m_busy_req_0(){
  if ( (rst.read() == 0ULL) ) {
    din_m_busy_req_0 = 1ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    default:
      switch( (sc_uint<2>)(global_state.read()) ) {
      case 0ULL: case 2ULL: 
        din_m_busy_req_0 = 0ULL;
        break;
      case 1ULL: 
        din_m_busy_req_0 = 1ULL;
        break;
      }
      break;
    }
  }
}
// resource: regr_en_sc_1
void dut::drive_dout_m_req_m_trig_req(){
  if ( (rst.read() == 0ULL) ) {
    dout_m_req_m_trig_req = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    default:
      switch( (sc_uint<2>)(global_state.read()) ) {
      case 1ULL: 
        dout_m_req_m_trig_req = (sc_uint<1> ) (dut_Not_1U_1U_1_3_out1.read());
        break;
      }
      break;
    }
  }
}
// resource: mux_1bx3i1c
void dut::drive_stall0(){
  switch( (sc_uint<2>)(global_state.read()) ) {
  default:
    stall0 = 0ULL;
    break;
  case 1ULL: 
    stall0 = (sc_uint<1> )dut_gen_busy_r_4_9_out1.read();
    break;
  case 2ULL: 
    stall0 = dut_And_1Ux1U_1U_4_7_out1.read();
    break;
  }
}
// resource: regr_en_sc_2
void dut::drive_global_state(){
  if ( (rst.read() == 0ULL) ) {
    global_state = 0ULL;
  } else {
    switch( (sc_uint<1>)(stall0.read()) ) {
    case 1ULL: 
      break;
    default:
      global_state = global_state_next.read();
      break;
    }
  }
}
// resource: dut_Mul_11U_0_4  instance: dut_Mul_11U_0_4_6
void dut::dut_Mul_11U_0_4_6(){
  dut_Mul_11U_0_4_6_out1 = din_data.read() * 7ULL;
}
// resource: mux_2bx2i2c
void dut::drive_global_state_next(){
  switch( (sc_uint<2>)(global_state.read()) ) {
  default:
    global_state_next = 2ULL;
    break;
  case 0ULL: case 2ULL: 
    global_state_next = 1ULL;
    break;
  }
}
void dut::drive_din_busy(){
  din_busy = (sc_uint<1> ) (((/*imp*/sc_uint<1> ) dut_gen_busy_r_4_9_out1.read()
             .range(2,2)));
}
// resource: dut_gen_busy_r_4  instance: dut_gen_busy_r_4_9
void dut::dut_gen_busy_r_4_9_p7(){
  dut_gen_busy_r_4_9_out1 = (sc_uint<3> ) (( (sc_biguint<3> )(sc_bv<3>)(
                            (sc_bv<1>)(dut_gen_busy_r_4_9_gnew_req.read()), 
                            (sc_bv<2>)(( (sc_biguint<2> )(sc_bv<2>)((sc_bv<1>)(
                            dut_gen_busy_r_4_9_gdiv.read()), 
                            (sc_bv<1>)(dut_gen_busy_r_4_9_din_gen_busy_din_m_data_is_invalid_next
                            .read())) ))) ));
}
// resource: dut_gen_busy_r_4  instance: dut_gen_busy_r_4_9
void dut::dut_gen_busy_r_4_9_p6(){
  dut_gen_busy_r_4_9_din_gen_busy_din_m_data_is_invalid_next = ~(sc_uint<1>)dut_gen_busy_r_4_9_gdiv
                                                               .read();
}
// resource: dut_gen_busy_r_4  instance: dut_gen_busy_r_4_9
void dut::dut_gen_busy_r_4_9_p5(){
  dut_gen_busy_r_4_9_gdiv = (sc_uint<1> ) ((sc_uint<1> )din_vld.read() & !
                            dut_gen_busy_r_4_9_gnew_req.read());
}
// resource: dut_gen_busy_r_4  instance: dut_gen_busy_r_4_9
void dut::dut_gen_busy_r_4_9_p4(){
  dut_gen_busy_r_4_9_gnew_req = (sc_uint<1> ) ((sc_uint<1> )din_m_busy_req_0
                                .read() & ( din_m_unvalidated_req.read() | 
                                din_vld.read() ));
}
// resource: regr_en_ss_1
void dut::drive_din_m_unvalidated_req(){
  if ( (rst.read() == 0ULL) ) {
    din_m_unvalidated_req = 1ULL;
  } else {
    switch( (sc_uint<1>)(!din_m_busy_req_0.read()) ) {
    case 1ULL: 
      din_m_unvalidated_req = (sc_uint<1> ) (dut_N_Muxb_1_2_8_4_4_out1.read());
      break;
    default:
      break;
    }
  }
}
// resource: dut_N_Muxb_1_2_8_4
void dut::dut_N_Muxb_1_2_8_4_4(){
  if ( din_m_busy_req_0.read() ) {
    dut_N_Muxb_1_2_8_4_4_out1 = (sc_uint<1> ) (din_m_unvalidated_req.read());
  } else {
    dut_N_Muxb_1_2_8_4_4_out1 = (sc_uint<1> ) (din_vld.read());
  }
}
void dut::drive_dout_vld(){
  dout_vld = (sc_uint<1> ) (dut_Or_1Ux1U_1U_4_2_out1.read());
}
// resource: dut_Or_1Ux1U_1U_4  instance: dut_Or_1Ux1U_1U_4_2
void dut::dut_Or_1Ux1U_1U_4_2(){
  dut_Or_1Ux1U_1U_4_2_out1 = (sc_uint<1> ) (dout_m_unacked_req.read() | (
                             sc_uint<1>)dut_Xor_1Ux1U_1U_1_1_out1.read());
}
// resource: regr_sc_1
void dut::drive_dout_m_unacked_req(){
  if ( (rst.read() == 0ULL) ) {
    dout_m_unacked_req = 0ULL;
  } else {
    dout_m_unacked_req = (sc_uint<1> ) (dut_And_1Ux1U_1U_4_7_out1.read());
  }
}
// resource: dut_And_1Ux1U_1U_4  instance: dut_And_1Ux1U_1U_4_7
void dut::dut_And_1Ux1U_1U_4_7(){
  dut_And_1Ux1U_1U_4_7_out1 = (sc_uint<1> ) (dout_busy.read() & dout_vld.read())
  ;
}
// resource: dut_Xor_1Ux1U_1U_1  instance: dut_Xor_1Ux1U_1U_1_1
void dut::dut_Xor_1Ux1U_1U_1_1(){
  dut_Xor_1Ux1U_1U_1_1_out1 = (sc_uint<1> ) (dout_m_req_m_trig_req.read() ^ 
                              dout_m_req_m_prev_trig_req.read());
}
// resource: regr_sc_1
void dut::drive_dout_m_req_m_prev_trig_req(){
  if ( (rst.read() == 0ULL) ) {
    dout_m_req_m_prev_trig_req = 0ULL;
  } else {
    dout_m_req_m_prev_trig_req = dout_m_req_m_trig_req.read();
  }
}
// resource: dut_Not_1U_1U_1  instance: dut_Not_1U_1U_1_3
void dut::dut_Not_1U_1U_1_3(){
  dut_Not_1U_1U_1_3_out1 = !dout_m_req_m_trig_req.read();
}
