// Generated by stratus_hls 23.02-s002  (100118.310516)
// Wed Nov 12 22:21:41 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Mul_8Ux3U_11U_1( in2, in1, out1 );

    input [7:0] in2;
    input [2:0] in1;
    output [10:0] out1;

    
    // rtl_process:dut_Mul_8Ux3U_11U_1/dut_Mul_8Ux3U_11U_1_thread_1
    assign out1 = {3'b000, in2} * {8'b00000000, in1};

endmodule

