// Generated by stratus_hls 23.02-s002  (100118.310516)
// Wed Nov 12 22:21:41 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Or_1Ux1U_1U_4( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:dut_Or_1Ux1U_1U_4/dut_Or_1Ux1U_1U_4_thread_1
    assign out1 = in2 | in1;

endmodule


