// Generated by stratus_hls 23.02-s002  (100118.310516)
// Thu Oct  2 18:47:02 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_N_Muxb_1_2_8_4( in3, in2, ctrl1, out1 );

    input in3;
    input in2;
    input ctrl1;
    output out1;
    reg out1;

    
    // rtl_process:dut_N_Muxb_1_2_8_4/dut_N_Muxb_1_2_8_4_thread_1
    always @*
      begin : dut_N_Muxb_1_2_8_4_thread_1
        case (ctrl1) 
          1'b1: 
            begin
              out1 = in2;
            end
          default: 
            begin
              out1 = in3;
            end
        endcase
      end

endmodule




