// Generated by stratus_hls 23.02-s002  (100118.310516)
// Thu Oct  2 18:47:02 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_Mul_11U_0_4( in1, out1 );

    input [7:0] in1;
    output [10:0] out1;

    
    // rtl_process:dut_Mul_11U_0_4/dut_Mul_11U_0_4_thread_1
    assign out1 = {3'b000, in1} * 11'd0007;

endmodule




