// Generated by stratus_hls 23.02-s002  (100118.310516)
// Thu Oct  2 18:47:02 2025
// from dut.cc

`timescale 1ps / 1ps


module dut_And_1Ux1U_1U_4( in2, in1, out1 );

    input in2;
    input in1;
    output out1;

    
    // rtl_process:dut_And_1Ux1U_1U_4/dut_And_1Ux1U_1U_4_thread_1
    assign out1 = in2 & in1;

endmodule




